services:
  # Backend services
  api:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://rafactory_rw:StrongP@ss!@db/rafactory
      - JWT_SECRET=dev_secret_change_in_production
    depends_on:
      - db
    profiles: ["dev", "staging", "test"]
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=rafactory
      - POSTGRES_USER=rafactory_rw
      - POSTGRES_PASSWORD=StrongP@ss!
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rafactory_rw -d rafactory"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles: ["dev", "staging", "test", "prod"]
    
  # Frontend services
  admin:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./frontend/admin:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    profiles: ["dev"]
    
  operator:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./frontend/operator:/app
    ports:
      - "5174:5174"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    profiles: ["dev"]
    
volumes:
  pgdata: 