"""Remove creation_date and check_sum from projects table

Revision ID: 1e0c0be8ce63
Revises: 00120674aa9c
Create Date: 2025-04-28 14:48:45.686146

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e0c0be8ce63'
down_revision = '00120674aa9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'check_sum')
    op.drop_column('projects', 'creation_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('creation_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('check_sum', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ### 