"""Initial migration

Revision ID: 87c511a4b679
Revises: 
Create Date: 2025-05-25 08:38:48.750091

"""
from alembic import op
import sqlalchemy as sa
import uuid


# revision identifiers, used by Alembic.
revision = '87c511a4b679'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('company_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('company_index >= 0 AND company_index <= 99', name='company_index_range'),
    sa.PrimaryKeyConstraint('guid'),
    sa.UniqueConstraint('company_index')
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('api_keys',
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('company_guid', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('scopes', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_guid'], ['companies.guid'], ),
    sa.PrimaryKeyConstraint('guid'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('projects',
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('in_production', sa.Boolean(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('company_guid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_guid'], ['companies.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_table('users',
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('company_guid', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('pwd_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('pin', sa.String(length=6), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('picture_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_guid'], ['companies.guid'], ),
    sa.PrimaryKeyConstraint('guid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('workstations',
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('company_guid', sa.UUID(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_guid'], ['companies.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_table('components',
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('project_guid', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('picture', sa.LargeBinary(), nullable=True),
    sa.Column('company_guid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_guid'], ['companies.guid'], ),
    sa.ForeignKeyConstraint(['project_guid'], ['projects.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_table('ui_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_guid', sa.UUID(), nullable=False),
    sa.Column('workstation_guid', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('json_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_guid'], ['companies.guid'], ),
    sa.ForeignKeyConstraint(['workstation_guid'], ['workstations.guid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow',
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('company_guid', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('workstation_guid', sa.UUID(), nullable=True),
    sa.Column('workstation_name', sa.String(), nullable=True),
    sa.Column('api_key_guid', sa.UUID(), nullable=True),
    sa.Column('user_guid', sa.UUID(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('action_type', sa.Enum('BarcodeScan', 'PieceCut', 'AssemblyWeld', 'QualityCheck', 'Packaging', 'Shipping', 'MaterialRequest', 'MaterialReceived', 'WorkstationLogin', 'WorkstationLogout', 'ErrorReport', 'MaintenanceRequest', 'SystemEvent', 'SoftDelete', 'Restore', name='workflowactiontype'), nullable=False),
    sa.Column('action_value', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_guid'], ['companies.guid'], ),
    sa.ForeignKeyConstraint(['user_guid'], ['users.guid'], ),
    sa.ForeignKeyConstraint(['workstation_guid'], ['workstations.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_table('articles',
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('consume_group_designation', sa.String(), nullable=True),
    sa.Column('consume_group_priority', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('category_designation', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('short_position', sa.String(), nullable=True),
    sa.Column('code_no_color', sa.String(), nullable=True),
    sa.Column('component_code', sa.String(), nullable=True),
    sa.Column('is_extra', sa.Boolean(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('surface', sa.Float(), nullable=True),
    sa.Column('angle1', sa.Float(), nullable=True),
    sa.Column('angle2', sa.Float(), nullable=True),
    sa.Column('unit_weight', sa.Float(), nullable=True),
    sa.Column('bar_length', sa.Float(), nullable=True),
    sa.Column('project_guid', sa.UUID(), nullable=False),
    sa.Column('component_guid', sa.UUID(), nullable=False),
    sa.Column('company_guid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_guid'], ['companies.guid'], ),
    sa.ForeignKeyConstraint(['component_guid'], ['components.guid'], ),
    sa.ForeignKeyConstraint(['project_guid'], ['projects.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_table('assemblies',
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('project_guid', sa.UUID(), nullable=False),
    sa.Column('component_guid', sa.UUID(), nullable=False),
    sa.Column('trolley_cell', sa.String(), nullable=True),
    sa.Column('trolley', sa.String(), nullable=True),
    sa.Column('cell_number', sa.Integer(), nullable=True),
    sa.Column('picture', sa.LargeBinary(), nullable=True),
    sa.Column('company_guid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_guid'], ['companies.guid'], ),
    sa.ForeignKeyConstraint(['component_guid'], ['components.guid'], ),
    sa.ForeignKeyConstraint(['project_guid'], ['projects.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_table('pieces',
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('piece_id', sa.String(), nullable=False),
    sa.Column('outer_length', sa.Integer(), nullable=True),
    sa.Column('angle_left', sa.Integer(), nullable=True),
    sa.Column('angle_right', sa.Integer(), nullable=True),
    sa.Column('orientation', sa.String(), nullable=True),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('assembly_width', sa.Integer(), nullable=True),
    sa.Column('assembly_height', sa.Integer(), nullable=True),
    sa.Column('trolley', sa.String(), nullable=True),
    sa.Column('cell', sa.String(), nullable=True),
    sa.Column('trolley_cell', sa.String(), nullable=True),
    sa.Column('operations', sa.String(), nullable=True),
    sa.Column('component_code', sa.String(), nullable=True),
    sa.Column('component_description', sa.String(), nullable=True),
    sa.Column('info2', sa.String(), nullable=True),
    sa.Column('info3', sa.String(), nullable=True),
    sa.Column('client', sa.String(), nullable=True),
    sa.Column('dealer', sa.String(), nullable=True),
    sa.Column('project_description', sa.String(), nullable=True),
    sa.Column('inner_length', sa.Integer(), nullable=True),
    sa.Column('reinforcement_code', sa.String(), nullable=True),
    sa.Column('reinforcement_length', sa.Integer(), nullable=True),
    sa.Column('hardware_info', sa.String(), nullable=True),
    sa.Column('glass_info', sa.String(), nullable=True),
    sa.Column('other_length', sa.Integer(), nullable=True),
    sa.Column('project_number', sa.String(), nullable=True),
    sa.Column('component_number', sa.String(), nullable=True),
    sa.Column('water_handle', sa.String(), nullable=True),
    sa.Column('segment_order', sa.String(), nullable=True),
    sa.Column('cutting_pattern', sa.String(), nullable=True),
    sa.Column('fixing_mode', sa.String(), nullable=True),
    sa.Column('material_type', sa.String(), nullable=True),
    sa.Column('project_code_parent', sa.String(), nullable=True),
    sa.Column('bar_id', sa.String(), nullable=True),
    sa.Column('bar_rest', sa.Integer(), nullable=True),
    sa.Column('bar_length', sa.Integer(), nullable=True),
    sa.Column('bar_cutting_tolerance', sa.Integer(), nullable=True),
    sa.Column('profile_code', sa.String(), nullable=True),
    sa.Column('profile_name', sa.String(), nullable=True),
    sa.Column('lamination', sa.String(), nullable=True),
    sa.Column('gasket', sa.String(), nullable=True),
    sa.Column('profile_width', sa.Integer(), nullable=True),
    sa.Column('profile_height', sa.Integer(), nullable=True),
    sa.Column('welding_tolerance', sa.Integer(), nullable=True),
    sa.Column('profile_color', sa.String(), nullable=True),
    sa.Column('profile_type_ra', sa.String(), nullable=True),
    sa.Column('profile_type', sa.String(), nullable=True),
    sa.Column('trolley_size', sa.String(), nullable=True),
    sa.Column('profile_code_with_color', sa.String(), nullable=True),
    sa.Column('project_guid', sa.UUID(), nullable=False),
    sa.Column('component_guid', sa.UUID(), nullable=False),
    sa.Column('assembly_guid', sa.UUID(), nullable=True),
    sa.Column('parent_assembly_trolley_cell', sa.String(), nullable=True),
    sa.Column('mullion_trolley_cell', sa.String(), nullable=True),
    sa.Column('glazing_bead_trolley_cell', sa.String(), nullable=True),
    sa.Column('picture', sa.LargeBinary(), nullable=True),
    sa.Column('project_phase', sa.String(), nullable=True),
    sa.Column('company_guid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assembly_guid'], ['assemblies.guid'], ),
    sa.ForeignKeyConstraint(['company_guid'], ['companies.guid'], ),
    sa.ForeignKeyConstraint(['component_guid'], ['components.guid'], ),
    sa.ForeignKeyConstraint(['project_guid'], ['projects.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    # ### end Alembic commands ###

    # ### Seeding initial data ###
    # Define table structures for data insertion
    companies_table = sa.table('companies',
        sa.column('guid', sa.UUID),
        sa.column('name', sa.String),
        sa.column('is_active', sa.Boolean)
    )
    users_table = sa.table('users',
        sa.column('guid', sa.UUID),
        sa.column('company_guid', sa.UUID),
        sa.column('email', sa.String),
        sa.column('pwd_hash', sa.String),
        sa.column('role', sa.String),
        sa.column('is_active', sa.Boolean)
    )

    # Generate a UUID for the system company
    system_company_guid = uuid.uuid4()

    # Insert the system company
    op.bulk_insert(companies_table,
        [
            {
                'guid': system_company_guid,
                'name': 'Ra Factory System',
                'is_active': True
            }
        ]
    )

    # Pre-hashed password for "password" using bcrypt
    hashed_password = '$2b$12$EixZaYVK1y.9i7L4a8Iqg.dF2s1C2A5iY3a6.e8j9D7gH6iI4o5uK'

    # Insert the system admin user
    op.bulk_insert(users_table,
        [
            {
                'guid': uuid.uuid4(),
                'company_guid': system_company_guid,
                'email': 'a.petrov@delice.bg',
                'pwd_hash': hashed_password,
                'role': 'SystemAdmin',
                'is_active': True
            }
        ]
    )


def downgrade() -> None:
    # ### Deleting seeded data ###
    op.execute("DELETE FROM users WHERE email = 'a.petrov@delice.bg'")
    op.execute("DELETE FROM companies WHERE name = 'Ra Factory System'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pieces')
    op.drop_table('assemblies')
    op.drop_table('articles')
    op.drop_table('workflow')
    op.drop_table('ui_templates')
    op.drop_table('components')
    op.drop_table('workstations')
    op.drop_table('users')
    op.drop_table('projects')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ### 