"""Add short_name, logo_path, is_active to companies table

Revision ID: 92cb5fead847
Revises: f346b6488b02
Create Date: 2025-04-27 13:28:43.979257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92cb5fead847'
down_revision = 'f346b6488b02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 